"""Adiciona stop_loss_percentage ao BettingProfile

Revision ID: 49d155a49be3
Revises: 
Create Date: 2025-10-02 18:47:28.351062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d155a49be3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stop_loss_percentage', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting_profiles', schema=None) as batch_op:
        batch_op.drop_column('stop_loss_percentage')

    # ### end Alembic commands ###
